#!/bin/bash

#  Copyright (C) 2015  Rafael Senties Martinelli 
#
#  This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License 3 as published by
#   the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA.

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR
#
#
if [ "$EUID" -ne 0 ]
  then echo "Please run as root."
  exit
fi
#
#

chmod -R 0755 $DIR
chown root:root -R $DIR

echo -e "\n Removing previous versions...\n"
./remove

echo -e "\nInstalling...\n"

cp -ar $DIR/usr/. /usr/

#
#
echo -e "\n \e[00;32m The installation is complete. I hope you enjoy the software! -RSM \e[00m"
